---
- name: template tftpd-hpa config
  template:
    src: default_tftpd_hpa.j2
    dest: /etc/default/tftpd-hpa
    backup: yes
  notify: restart tftp
  when: ansible_os_family == "Debian"

- name: create tftp directory
  file:
    path: "{{ tftp_dir }}"
    mode: 0755
    state: directory
  notify: restart tftp

- name: create tftp pxe directories
  file:
    path: "{{ tftp_dir }}/{{ item }}"
    mode: 0755
    state: directory
  with_items: "{{ tftp_pxe_dir }}"
  notify: restart tftp

- name: copy syslinux binaries to tftp directory
  copy:
    src: "{{ item }}"
    dest: "{{ tftp_dir }}"
    remote_src: yes
    mode: 0644
  with_items: "{{ tftp_syslinux_binary }}"
  notify: restart tftp

- name: template xinetd tftp config
  template:
    src: xinetd_tftp.j2
    dest: /etc/xinetd.d/tftp
    backup: yes
  notify: restart tftp
  when: ansible_os_family == "RedHat"

- meta: flush_handlers


- name: Restart the tftpd service
  systemd:
    name: "{{ tftp_service }"
    state: restarted
    enabled: yes
  register: tftpd_hpa_restarted
  when: tftpd_require_restart | default(false)


- name: Verify the tftpd service is listening
  shell: nmap -sU -p 69 0.0.0.0 | grep -q open
  when: tftpd_hpa_restarted is changed
  ignore_errors: yes
  register: tftpd_start_attempt
  until: tftpd_start_attempt.rc == 0
  retries: 5
  delay: 5

- name: Get tftpd journald logs if service does not appear to be up
  shell: journalctl _SYSTEMD_INVOCATION_ID=`systemctl show -p InvocationID --value {{ tftp_service }}.service`
  register: tftpd_hpa_journal
  when: tftpd_start_attempt.failed | default(false)

- fail:
    msg: "{{ tftpd_hpa_journal.stdout_lines }}"
  when: tftpd_start_attempt.failed | default(false)
