---
- name: add tftp group
  group:
    name: "{{ tftp_group }}"
    system: yes
    state: present

- name: add tftp user
  user:
    name: "{{ tftp_user }}"
    group: "{{ tftp_group }}"
    system: yes
    createhome: no
    password: !
    shell: /bin/false
    state: present

- name: create tftp directory
  file:
    path: "{{ tftp_dir }}"
    mode: 0755
    state: directory

- name: create tftp pxe directories
  file:
    path: "{{ tftp_dir }}/{{ item }}"
    mode: 0755
    state: directory
  with_items: "{{ tftp_pxe_dir }}"

- name: copy syslinux binaries to tftp directory
  copy:
    src: "{{ item }}"
    dest: "{{ tftp_dir }}"
    remote_src: yes
    mode: 0644
  with_items: "{{ tftp_syslinux_binary }}"

- name: template tftpd-hpa config
  template:
    src: default_tftpd_hpa.j2
    dest: /etc/default/tftpd-hpa
    backup: yes
  register: tftpd_config_copy
  when: ansible_os_family == "Debian"

- name: template xinetd tftp config
  template:
    src: xinetd_tftp.j2
    dest: /etc/xinetd.d/tftp
    backup: yes
  register: tftpd_config_copy
  when: ansible_os_family == "RedHat"

- name: Restart the tftpd service
  systemd:
    name: tftpd-hpa
    state: restarted
    enabled: yes
  register: tftpd_hpa_restarted
  when: tftpd_config_copy is changed

- name: Verify the tftpd service is listening
  wait_for:
    host: "{{ tftp_hpa_address.split(':')[0] }}"
    port: "{{ tftp_hpa_address.split(':')[1]"
    delay: 5
  when: tftpd_hpa_restarted is changed
  ignore_errors: yes
  register: tftpd_start_attempt

- name: Get tftpd journald logs if service does not appear to be up
  shell: journalctl _SYSTEMD_INVOCATION_ID=`systemctl show -p InvocationID --value tftpd-hpa.service`
  register: tftpd_hpa_journal
  when: tftpd_start_attempt.failed is defined and tftpd_start_attempt.failed == True

- fail:
    msg: "{{ tftpd_hpa_journal.stdout_lines }}"
  when: tftpd_start_attempt.failed is defined and tftpd_start_attempt.failed == True
