---
- name: Disable SELinux
  selinux:
    state: disabled
  when:
    - ansible_os_family == "RedHat"

- name: Set FirewallD public zone to allow-all
  command: firewall-cmd --permanent --zone=public --set-target=ACCEPT
  when:
    - ansible_os_family == "RedHat"

- name: Create TFTP system group
  group:
    name: "{{ tftp_group }}"
    system: yes
    state: present

- name: Create TFTP system user
  user:
    name: "{{ tftp_user }}"
    group: "{{ tftp_group }}"
    system: yes
    createhome: no
    password: !
    shell: /bin/false
    state: present

- name: "Install {{ tftp_pkg }}"
  package:
    name: "{{ tftp_pkg }}"
    state: present

- name: Enable TFTP Server
  systemd:
    name: "{{ tftp_service }}"
    enabled: yes
    daemon_reload: yes
