---
- name: Disable SELinux
  selinux:
    state: disabled
  when:
    - ansible_os_family == "RedHat"

- name: Get FirewallD public zone target
  command: firewall-cmd --zone public --get-target --permanent
  register: firewalld_public_target
  changed_when: False
  when:
    - ansible_os_family == "RedHat"

- name: Set FirewallD public zone to allow-all
  command: firewall-cmd --permanent --set-target=ACCEPT
  when:
    - firewalld_public_target.stdout != "ACCEPT"
    - ansible_os_family == "RedHat""

- name: Create TFTP system group
  group:
    name: "{{ tftp_group }}"
    system: yes
    state: present

- name: Create TFTP system user
  user:
    name: "{{ tftp_user }}"
    group: "{{ tftp_group }}"
    system: yes
    createhome: no
    password: !
    shell: /bin/false
    state: present

- name: "Install {{ tftp_pkg }}"
  package:
    name: "{{ tftp_pkg }}"
    state: present

- name: Enable TFTP Server
  systemd:
    name: "{{ tftp_service }}"
    enabled: yes
    daemon_reload: yes

- name: Create systemd override for TFTP service
  block:
    - name: Create systemd TFTP service.d directory
      file:
        path: "/etc/systemd/system/tftp.service.d"
        state: directory

    - name: Create systemd TFTP override config
      template:
        src: tftp.override.j2
        dest: "/etc/systemd/system/tftp.service.d/override.conf"
        mode: 0755
      register: tftp_override

    - name: Reload systemd service and restart tftp service # noqa 503
      systemd:
        name: "tftp"
        state: restarted
        enabled: yes
        daemon_reload: yes
      when: tftp_override.changed
  when:
    - ansible_os_family == "RedHat"
