---
- name: "Disable SELinux, Configure FirewallD ports to ACCEPT [RHEL/CentOS]"
  block:
    - name: Disable SELinux
      selinux:
        state: disabled
    - name: Configure Firewalld allowed ports
      firewalld:
        port: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop: "{{ tftp_allowed_ports }}"
  when: ansible_os_family == "RedHat"

- name: Create TFTP system group
  group:
    name: "{{ tftp_group }}"
    system: yes
    state: present

- name: Create TFTP system user
  user:
    name: "{{ tftp_user }}"
    group: "{{ tftp_group }}"
    system: yes
    createhome: no
    password: !
    shell: /bin/false
    state: present

- name: "Install {{ tftp_pkg }}"
  package:
    name: "{{ tftp_pkg }}"
    state: present

- name: Enable TFTP Server
  systemd:
    name: "{{ tftp_service }}"
    enabled: yes
    daemon_reload: yes

- name: Create systemd override for TFTP service
  block:
    - name: Create systemd TFTP service.d directory
      file:
        path: "/etc/systemd/system/tftp.service.d"
        state: directory

    - name: Create systemd TFTP override config
      template:
        src: tftp.override.j2
        dest: "/etc/systemd/system/tftp.service.d/override.conf"
        mode: 0755
      register: tftp_override

    - name: Reload systemd service and restart tftp service # noqa 503
      systemd:
        name: "tftp"
        state: restarted
        enabled: yes
        daemon_reload: yes
      when: tftp_override.changed
  when:
    - ansible_os_family == "RedHat"
